services:
    postgres:
        container_name: cash-flow
        image: postgres:17
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        ports:
            - 5436:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - cash-flow

volumes:
    postgres_data:

networks:
    cash-flow:
