services:
    postgres:
        container_name: cash-flow
        image: postgres:17
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        ports:
            - 5436:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - cash-flow

    rabbitmq:
        image: rabbitmq:3.13-management
        container_name: cash-flow-rmq
        restart: always
        ports:
            - '5672:5672'
            - '15672:15672'
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        networks:
            - cash-flow

volumes:
    postgres_data:

networks:
    cash-flow:
